spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: student-service
  datasource:
    url: jdbc:h2:file:C:\Users\marcos.cavalheiro\Documents\Projetos\Microservices\TreinamentoMicroservices\datasource\datasource
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8200

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka